name: CI/CD - MovieFlix Analytics

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: docker build -t movieflix-analytics:latest .

      - name: Run container for simple test
        run: |
          docker run -d -p 3000:3000 --name movieflix_test movieflix-analytics:latest
          for i in {1..12}; do
            if curl --fail http://localhost:3000/ >/dev/null 2>&1; then
              echo "app responding" && break
            fi
            echo "waiting..." && sleep 2
          done
          curl --fail http://localhost:3000/ || (docker logs movieflix_test && exit 1)
          docker stop movieflix_test && docker rm movieflix_test

      - name: Tag and push
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        run: |
          IMAGE_NAME=${DOCKER_USER}/movieflix-analytics
          docker tag movieflix-analytics:latest $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest
